# Generated by Django 3.0.6 on 2020-05-28 21:29

from django.db import migrations, models
import django_scorecard.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challenge',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='overview',
            name='commitments_image',
            field=models.ImageField(blank=True, null=True, storage=django_scorecard.storage_backends.PublicMediaStorage(), upload_to='images/'),
        ),
        migrations.AddField(
            model_name='overview',
            name='story_image',
            field=models.ImageField(blank=True, null=True, storage=django_scorecard.storage_backends.PublicMediaStorage(), upload_to='images/'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
