# Generated by Django 3.0.6 on 2020-05-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0002_auto_20200528_1429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ('order_id',)},
        ),
        migrations.AlterModelOptions(
            name='challenge',
            options={'ordering': ('order_id',)},
        ),
        migrations.AlterModelOptions(
            name='recommendation',
            options={'ordering': ('order_id',)},
        ),
        migrations.AddField(
            model_name='achievement',
            name='order_id',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='challenge',
            name='order_id',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='order_id',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
