# Generated by Django 3.0.6 on 2020-05-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0004_auto_20200528_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitment',
            name='has_approved_funding',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='commitment',
            name='has_begun_implementation',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='commitment',
            name='has_detailed_plan',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='commitment',
            name='is_complete',
            field=models.NullBooleanField(),
        ),
    ]
