# Generated by Django 3.0.6 on 2020-05-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0005_auto_20200529_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commitment',
            options={'ordering': ('order_num', 'order_letter')},
        ),
        migrations.AlterModelOptions(
            name='commitmentcategory',
            options={'ordering': ('order_num',), 'verbose_name_plural': 'commitment categories'},
        ),
        migrations.AddField(
            model_name='overview',
            name='commitment_chart_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='status',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
    ]
