# Generated by Django 3.0.6 on 2020-06-02 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0006_auto_20200529_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='overview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scorecard.Overview'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='overview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scorecard.Overview'),
        ),
        migrations.AddField(
            model_name='commitment',
            name='overview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scorecard.Overview'),
        ),
        migrations.AddField(
            model_name='commitmentcategory',
            name='overview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scorecard.Overview'),
        ),
        migrations.AddField(
            model_name='document',
            name='overview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scorecard.Overview'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='overview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scorecard.Overview'),
        ),
        migrations.AddField(
            model_name='status',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
