# Generated by Django 3.0.6 on 2020-06-03 05:45

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0007_auto_20200601_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='description_mo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='name_mo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='order_id_en',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='order_id_mo',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='description_mo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='name_mo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='order_id_en',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='order_id_mo',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='commitment',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commitment',
            name='description_mo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commitment',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commitment',
            name='name_mo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commitment',
            name='order_letter_en',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='commitment',
            name='order_letter_mo',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='commitment',
            name='order_num_en',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='commitment',
            name='order_num_mo',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='commitment',
            name='original_timeline_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commitment',
            name='original_timeline_mo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commitmentcategory',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commitmentcategory',
            name='name_mo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commitmentcategory',
            name='order_num_en',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='commitmentcategory',
            name='order_num_mo',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='description_mo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='name_mo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='overview',
            name='achievements_text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overview',
            name='achievements_text_mo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overview',
            name='challenges_text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overview',
            name='challenges_text_mo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overview',
            name='commitment_chart_text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overview',
            name='commitment_chart_text_mo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overview',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='overview',
            name='name_mo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='overview',
            name='story_part1_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overview',
            name='story_part1_mo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overview',
            name='story_part2_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overview',
            name='story_part2_mo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overview',
            name='story_part3_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overview',
            name='story_part3_mo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='description_mo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_mo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='order_id_en',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='order_id_mo',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='description_mo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='status_en',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='completed', max_length=100, no_check_for_status=True, null=True, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='status',
            name='status_mo',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='completed', max_length=100, no_check_for_status=True, null=True, verbose_name='status'),
        ),
    ]
