# Generated by Django 3.0.6 on 2020-06-05 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0008_auto_20200602_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='overview',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
