# Generated by Django 3.0.6 on 2020-06-06 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0009_overview_subtitle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ('date',), 'verbose_name_plural': 'statuses'},
        ),
    ]
