# Generated by Django 3.0.6 on 2020-06-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0011_document_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='overview',
            name='about_us',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='overview',
            name='methodology',
            field=models.TextField(blank=True),
        ),
    ]
