# Generated by Django 3.0.6 on 2020-06-11 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0012_auto_20200610_2052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commitment',
            options={'ordering': ('order_num', 'id', 'order_letter')},
        ),
        migrations.RemoveField(
            model_name='status',
            name='status_en',
        ),
        migrations.RemoveField(
            model_name='status',
            name='status_mo',
        ),
    ]
