# Generated by Django 3.0.6 on 2020-06-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0013_auto_20200610_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='overview',
            name='about_us_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overview',
            name='about_us_mo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overview',
            name='methodology_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overview',
            name='methodology_mo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
