# Generated by Django 3.0.6 on 2020-06-12 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0014_auto_20200610_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='order_id_en',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='order_id_mo',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='order_id_en',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='order_id_mo',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='order_id_en',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='order_id_mo',
        ),
    ]
