# Generated by Django 3.0.6 on 2020-06-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0017_auto_20200612_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='overview',
            name='case_page',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='overview',
            name='report_en',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='overview',
            name='report_mn',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='overview',
            name='report_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='overview',
            name='report_name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='overview',
            name='report_name_mn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
