# Generated by Django 3.0.6 on 2020-06-18 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0018_auto_20200617_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commitment',
            name='order_letter_en',
        ),
        migrations.RemoveField(
            model_name='commitment',
            name='order_letter_mn',
        ),
        migrations.RemoveField(
            model_name='commitment',
            name='order_num_en',
        ),
        migrations.RemoveField(
            model_name='commitment',
            name='order_num_mn',
        ),
    ]
