# Generated by Django 3.0.6 on 2020-06-18 01:59

from django.db import migrations, models
import django_scorecard.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0019_auto_20200617_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_en',
            field=models.FileField(blank=True, null=True, storage=django_scorecard.storage_backends.PrivateMediaStorage(), upload_to='cases/'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_mn',
            field=models.FileField(blank=True, null=True, storage=django_scorecard.storage_backends.PrivateMediaStorage(), upload_to='cases/'),
        ),
    ]
