# Generated by Django 3.0.6 on 2020-06-18 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0020_auto_20200617_1859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('date',)},
        ),
    ]
