# Generated by Django 3.0.6 on 2020-06-18 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0021_auto_20200618_1319'),
        ('scorecard', '0021_auto_20200618_1347'),
    ]

    operations = [
    ]
